
import java.awt.Dimension;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;


public class Galletas extends javax.swing.JFrame {
    FileOutputStream archi= null;
    PrintWriter pw;
    String cadena="";

    public Galletas() {
        initComponents();
        this.setSize(new Dimension(340,400));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TGalletas = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        GNuez = new javax.swing.JRadioButton();
        GAvena = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        PaginaPrincipal = new javax.swing.JButton();
        VerificarOrden = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        Titulo.setText("GALLETAS");
        getContentPane().add(Titulo);
        Titulo.setBounds(100, 50, 144, 25);

        TGalletas.add(GNuez);
        GNuez.setText("Galletas de Nuez");
        GNuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GNuezActionPerformed(evt);
            }
        });
        getContentPane().add(GNuez);
        GNuez.setBounds(120, 100, 130, 23);

        TGalletas.add(GAvena);
        GAvena.setText("Galletas de Avena");
        getContentPane().add(GAvena);
        GAvena.setBounds(120, 140, 130, 23);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(80, 190, 71, 23);

        PaginaPrincipal.setText("Pagina Principal");
        PaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(PaginaPrincipal);
        PaginaPrincipal.setBounds(180, 190, 120, 23);

        VerificarOrden.setText("Verificar Orden");
        VerificarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(VerificarOrden);
        VerificarOrden.setBounds(110, 250, 140, 23);

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galletas2.png"))); // NOI18N
        getContentPane().add(Imagen);
        Imagen.setBounds(0, 0, 350, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        int Precio=0;
        String Tam = null;
        String NombreP = null;
        
        if(GNuez.isSelected())
        {
            Precio=20; 
            NombreP="Galleta de Nuez";
        }
        if(GAvena.isSelected())
        {
            Precio=20; 
            NombreP="Galleta de Avena";
        }
        
       cadena=cadena+"\nNombre del Postre: "+NombreP+"\nCosto del Postre: $"+Precio;
       FileOutputStream fos=null;
       PrintWriter pw;
        try{
              fos=new FileOutputStream("Cafeteria.txt",true);             
           }catch(IOException ex){
           }
            cadena=cadena+"\n";
            pw=new PrintWriter(fos);
            pw.write(cadena);
            pw.close();
          try{
               fos.close();
             }catch(IOException ex){
                   
            }
    }//GEN-LAST:event_AceptarActionPerformed

    private void GNuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GNuezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GNuezActionPerformed

    private void PaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaPrincipalActionPerformed
        // TODO add your handling code here:
         Cafeteria Ct =new Cafeteria();
         hide();
         Ct.setVisible(true);
    }//GEN-LAST:event_PaginaPrincipalActionPerformed

    private void VerificarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarOrdenActionPerformed
        // TODO add your handling code here:
        Verificacion_Orden vo =new Verificacion_Orden();
        hide();
        vo.setVisible(true);
    }//GEN-LAST:event_VerificarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Galletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Galletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Galletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Galletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Galletas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JRadioButton GAvena;
    private javax.swing.JRadioButton GNuez;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton PaginaPrincipal;
    private javax.swing.ButtonGroup TGalletas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VerificarOrden;
    // End of variables declaration//GEN-END:variables
}
