
import java.awt.Dimension;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;



public class Jugos extends javax.swing.JFrame {

    FileOutputStream archi= null;
    PrintWriter pw;
    String cadena="";
    
    public Jugos() {
        initComponents();
        this.setSize(new Dimension(400,390));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TJugos = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        JNaranja = new javax.swing.JRadioButton();
        JVerde = new javax.swing.JRadioButton();
        JLimon = new javax.swing.JRadioButton();
        ANatural = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        PaginaPrincipal = new javax.swing.JButton();
        TextoTamaño = new javax.swing.JLabel();
        Tamaño = new javax.swing.JComboBox<>();
        VerificarOrden = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Titulo.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        Titulo.setText("JUGOS");
        getContentPane().add(Titulo);
        Titulo.setBounds(160, 10, 97, 37);

        JNaranja.setBackground(new java.awt.Color(255, 255, 255));
        TJugos.add(JNaranja);
        JNaranja.setText("Jugo de Naranja");
        getContentPane().add(JNaranja);
        JNaranja.setBounds(62, 66, 120, 23);

        JVerde.setBackground(new java.awt.Color(255, 255, 255));
        TJugos.add(JVerde);
        JVerde.setText("Jugo Verde");
        JVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JVerdeActionPerformed(evt);
            }
        });
        getContentPane().add(JVerde);
        JVerde.setBounds(62, 124, 120, 23);

        JLimon.setBackground(new java.awt.Color(255, 255, 255));
        TJugos.add(JLimon);
        JLimon.setText("Jugo de Limón");
        getContentPane().add(JLimon);
        JLimon.setBounds(230, 70, 120, 23);

        ANatural.setBackground(new java.awt.Color(255, 255, 255));
        TJugos.add(ANatural);
        ANatural.setText("Agua Natural");
        getContentPane().add(ANatural);
        ANatural.setBounds(233, 124, 110, 23);

        Aceptar.setBackground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(110, 230, 71, 23);

        PaginaPrincipal.setText("Pagina Principal");
        PaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(PaginaPrincipal);
        PaginaPrincipal.setBounds(210, 230, 107, 23);

        TextoTamaño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TextoTamaño.setText("Tamaño del jugo:");
        getContentPane().add(TextoTamaño);
        TextoTamaño.setBounds(70, 180, 130, 15);

        Tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........", "Pequeño", "Mediano", "Grande" }));
        getContentPane().add(Tamaño);
        Tamaño.setBounds(220, 180, 100, 20);

        VerificarOrden.setText("Verificar Orden ");
        VerificarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(VerificarOrden);
        VerificarOrden.setBounds(140, 280, 140, 23);

        Imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugos2.jpg"))); // NOI18N
        Imagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Imagen.setMaximumSize(new java.awt.Dimension(1400, 621));
        Imagen.setPreferredSize(new java.awt.Dimension(1228, 1221));
        getContentPane().add(Imagen);
        Imagen.setBounds(0, 0, 400, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaPrincipalActionPerformed
        // TODO add your handling code here:
           Cafeteria Ct =new Cafeteria();
           hide();
           Ct.setVisible(true);
    }//GEN-LAST:event_PaginaPrincipalActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        int Precio =0;
        String Tam = null;
        
        switch(Tamaño.getSelectedIndex())
            {
              case 1: Precio=15;
                      Tam="Pequeño";
              break;
              case 2: Precio=23;
                      Tam="Mediano";
              break;
              case 3: Precio=30;
                      Tam="Grande";
              break;
            }
        String NombreP = null;
         if(JNaranja.isSelected())
         {
             NombreP="Jugo de Naranja";
         }
         if(JVerde.isSelected())
         {
             NombreP="Jugo Verde";
         }
         if(JLimon.isSelected())
         {
             NombreP="Jugo de Limon";
         }
         if(ANatural.isSelected())
         {
             NombreP="Agua Natural";
         }
         
       cadena=cadena+"\nNombre de la bebida: "+NombreP+"\nTamaño de la bebida: "+Tam+"\nCosto de la bebida: $"+Precio;
       FileOutputStream fos=null;
       PrintWriter pw;
        try{
              fos=new FileOutputStream("Cafeteria.txt",true);
           }catch(IOException ex){
           }
            cadena=cadena+"\n";
            pw=new PrintWriter(fos);
            pw.write(cadena);
            pw.close();
          try{
               fos.close();
             }catch(IOException ex){
                   
            }
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void JVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JVerdeActionPerformed

    private void VerificarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarOrdenActionPerformed
        // TODO add your handling code here:
        Verificacion_Orden vo =new Verificacion_Orden();
        hide();
        vo.setVisible(true);
        
    }//GEN-LAST:event_VerificarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ANatural;
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Imagen;
    private javax.swing.JRadioButton JLimon;
    private javax.swing.JRadioButton JNaranja;
    private javax.swing.JRadioButton JVerde;
    private javax.swing.JButton PaginaPrincipal;
    private javax.swing.ButtonGroup TJugos;
    private javax.swing.JComboBox<String> Tamaño;
    private javax.swing.JLabel TextoTamaño;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VerificarOrden;
    // End of variables declaration//GEN-END:variables
}
