
import java.awt.Dimension;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;


public class Pasteles extends javax.swing.JFrame {

    FileOutputStream archi= null;
    PrintWriter pw;
    String cadena="";

    public Pasteles() {
        initComponents();
        this.setSize(new Dimension(300,400));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPasteles = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        POreo = new javax.swing.JRadioButton();
        PFresa = new javax.swing.JRadioButton();
        PCajeta = new javax.swing.JRadioButton();
        P3Leches = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        PaginaPrincipal = new javax.swing.JButton();
        VerificarOrden = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Titulo.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("PASTELES");
        getContentPane().add(Titulo);
        Titulo.setBounds(61, 11, 143, 25);

        TPasteles.add(POreo);
        POreo.setText("Pastel de Queso con Oreo");
        getContentPane().add(POreo);
        POreo.setBounds(53, 64, 151, 23);

        TPasteles.add(PFresa);
        PFresa.setText("Pastel de Queso con Fresa");
        getContentPane().add(PFresa);
        PFresa.setBounds(53, 105, 153, 23);

        TPasteles.add(PCajeta);
        PCajeta.setText("Pastel de Queso con Cajeta");
        getContentPane().add(PCajeta);
        PCajeta.setBounds(53, 146, 159, 23);

        TPasteles.add(P3Leches);
        P3Leches.setText("Pastel de 3 Leches");
        getContentPane().add(P3Leches);
        P3Leches.setBounds(53, 187, 115, 23);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(35, 242, 71, 23);

        PaginaPrincipal.setText("Pagina Principal");
        PaginaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(PaginaPrincipal);
        PaginaPrincipal.setBounds(120, 240, 130, 23);

        VerificarOrden.setText("Verificar Orden ");
        VerificarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(VerificarOrden);
        VerificarOrden.setBounds(70, 300, 120, 23);

        Imagen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pastel.jpg"))); // NOI18N
        getContentPane().add(Imagen);
        Imagen.setBounds(0, 0, 280, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        int Precio=0;
        String Tam = null;
        String NombreP = null;
        
         if(POreo.isSelected())
            {
               Precio=30;  
               NombreP="Pastel de queso con oreo";
            }
         if(PFresa.isSelected())
            {
               Precio=30;
               NombreP="Pastel de queso con fresa";
            }
         if(PCajeta.isSelected())
            {
               Precio=35;
               NombreP="Pastel de queso con cajeta";
            }
         if(P3Leches.isSelected())
            {
               Precio=35;
               NombreP="Pastel de 3 leches";
            }
            
       cadena=cadena+"\nNombre del Postre: "+NombreP+"\nCosto del Postre: $"+Precio;
       FileOutputStream fos=null;
       PrintWriter pw;
        try{
              fos=new FileOutputStream("Cafeteria.txt",true);
           }catch(IOException ex){
           }
            cadena=cadena+"\n";
            pw=new PrintWriter(fos);
            pw.write(cadena);
            pw.close();
          try{
               fos.close();
             }catch(IOException ex){
                   
            }
    }//GEN-LAST:event_AceptarActionPerformed

    private void VerificarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarOrdenActionPerformed
        // TODO add your handling code here:
        Verificacion_Orden vo =new Verificacion_Orden();
        hide();
        vo.setVisible(true);
    }//GEN-LAST:event_VerificarOrdenActionPerformed

    private void PaginaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaPrincipalActionPerformed
        // TODO add your handling code here:
         Cafeteria Ct =new Cafeteria();
         hide();
         Ct.setVisible(true);
    }//GEN-LAST:event_PaginaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pasteles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Imagen;
    private javax.swing.JRadioButton P3Leches;
    private javax.swing.JRadioButton PCajeta;
    private javax.swing.JRadioButton PFresa;
    private javax.swing.JRadioButton POreo;
    private javax.swing.JButton PaginaPrincipal;
    private javax.swing.ButtonGroup TPasteles;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VerificarOrden;
    // End of variables declaration//GEN-END:variables
}
